name = "pycombiner"
version = "2.0.0"
description = "Combine that all your python files in your project sequential into one by the relationship of import satement."

license='BSD License'
authors = [
    "KissesJun <meng.junqing1022@gmail.com>",
]
maintainers = [
    "KissesJun <meng.junqing1022@gmail.com>",
]
readme='readme.md'
homepage = "https://KissesJun.github.io/"
repository = "https://KissesJun.com/KissesJun/pycombiner.git"

[tool.poetry]
packages = [
    { include = "examples", format="sdist" },
]
# ...
include = ["readme.md"]

[tool.poetry.scripts]
pycombiner = 'pycombiner.__main__:run'